// CountryCityData.swift
// Xplora

import Foundation

enum CountryCityData {
    static let cities: [String: [String]] = [
        "AR": ["Buenos Aires", "Patagonia", "Mendoza", "Bariloche", "Córdoba"],
        "AU": ["Sydney", "Melbourne", "Brisbane", "Perth", "Cairns"],
        "AT": ["Vienna", "Salzburg", "Innsbruck", "Graz"],
        "BE": ["Brussels", "Bruges", "Ghent", "Antwerp"],
        "BR": ["Rio de Janeiro", "São Paulo", "Salvador", "Florianópolis", "Manaus"],
        "CA": ["Toronto", "Vancouver", "Montreal", "Quebec City", "Banff"],
        "CL": ["Santiago", "Patagonia", "Valparaíso", "San Pedro de Atacama"],
        "CN": ["Beijing", "Shanghai", "Xi'an", "Chengdu", "Guilin"],
        "CO": ["Bogotá", "Cartagena", "Medellín", "Santa Marta"],
        "HR": ["Dubrovnik", "Split", "Zagreb", "Hvar", "Plitvice"],
        "CZ": ["Prague", "Brno", "Český Krumlov"],
        "DK": ["Copenhagen", "Aarhus", "Odense"],
        "EG": ["Cairo", "Luxor", "Aswan", "Alexandria", "Sharm el-Sheikh"],
        "FI": ["Helsinki", "Rovaniemi", "Turku", "Tampere"],
        "FR": ["Paris", "Normandy", "Nice", "Lyon", "Marseille", "Bordeaux"],
        "DE": ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Dresden"],
        "GR": ["Athens", "Santorini", "Mykonos", "Thessaloniki", "Crete"],
        "HU": ["Budapest", "Pécs", "Debrecen", "Eger"],
        "IS": ["Reykjavik", "Akureyri", "Vík", "Snæfellsnes"],
        "IN": ["Delhi", "Mumbai", "Jaipur", "Goa", "Varanasi", "Agra"],
        "ID": ["Bali", "Jakarta", "Lombok", "Komodo", "Yogyakarta"],
        "IE": ["Dublin", "Galway", "Cork", "Killarney"],
        "IL": ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"],
        "IT": ["Rome", "Florence", "Venice", "Milan", "Amalfi", "Sicily"],
        "JP": ["Tokyo", "Kyoto", "Osaka", "Hiroshima", "Nara", "Hokkaido"],
        "JO": ["Amman", "Petra", "Wadi Rum", "Aqaba"],
        "KE": ["Nairobi", "Maasai Mara", "Mombasa", "Lamu"],
        "MX": ["Mexico City", "Cancún", "Oaxaca", "Tulum", "Guadalajara"],
        "MA": ["Marrakech", "Fes", "Casablanca", "Chefchaouen", "Essaouira"],
        "NL": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
        "NZ": ["Auckland", "Queenstown", "Christchurch", "Wellington"],
        "NO": ["Oslo", "Bergen", "Tromsø", "Stavanger", "Lofoten"],
        "PE": ["Lima", "Cusco", "Machu Picchu", "Arequipa"],
        "PH": ["Manila", "Palawan", "Cebu", "Siargao", "Boracay"],
        "PL": ["Warsaw", "Kraków", "Gdańsk", "Wrocław"],
        "PT": ["Lisbon", "Porto", "Algarve", "Sintra", "Madeira"],
        "RO": ["Bucharest", "Transylvania", "Sibiu", "Cluj-Napoca"],
        "RU": ["Moscow", "St. Petersburg", "Kazan", "Sochi"],
        "SA": ["Riyadh", "Jeddah", "AlUla", "Neom"],
        "ZA": ["Cape Town", "Johannesburg", "Kruger", "Durban"],
        "KR": ["Seoul", "Busan", "Jeju", "Gyeongju"],
        "ES": ["Madrid", "Barcelona", "Seville", "Granada", "Valencia"],
        "SE": ["Stockholm", "Gothenburg", "Malmö", "Uppsala"],
        "CH": ["Zurich", "Geneva", "Bern", "Interlaken", "Lucerne"],
        "TH": ["Bangkok", "Chiang Mai", "Phuket", "Koh Samui"],
        "TR": ["Istanbul", "Cappadocia", "Antalya", "Bodrum"],
        "UA": ["Kyiv", "Lviv", "Odesa"],
        "GB": ["London", "Edinburgh", "Oxford", "Manchester", "Bath"],
        "US": ["New York", "Los Angeles", "San Francisco", "Chicago", "New Orleans"],
        "VN": ["Hanoi", "Ho Chi Minh City", "Hội An", "Da Nang"],
    ]
}
